- hosts: yandex
  tasks:
    - name: install cowsay
      ansible.builtin.apt:
        name: cowsay
        state: present
      become: yes
      tags: cowsay
      
    - name: cowsay say
      command: "/usr/games/cowsay {{ server_name_full | upper }}"
      register: cowsay_result
      become: yes
      
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
      become: yes
    
    - name: update nginx config
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx
      become: yes

    - name: update index content
      ansible.builtin.template:
        src: templates/index.html.j2
        dest: "{{root_dir}}/index.html"
      become: yes
  
  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes
